#!/bin/bash



tableName="$1"


read -p "Enter the number of columns: " columnCount

# Column count validation ^must start $must end -- not negative
if ! [[ "$columnCount" =~ ^[0-9]+$ ]]; then
    echo "Invalid number of columns. Must be a positive integer and not null."
    exit 1
fi


# Flag to set pk true if set
pkFlag=true

# Loop over columns
for ((i=1; i<=columnCount; i++))
 do 
    row=""
    echo "You are in column $i:"
    read -p " Enter ColumnName : " columnName # Set column name
    # Space constraint
    if [[ "$columnName" =~ ^[a-zA-Z]+$ ]]
     then
     row+="$columnName"
    else    
         echo "Invalid Column Name"
        ((i--)) # Go back to same column to rename
        continue # Skip to next loop
    fi

    #col type 
    read -p "please enter column Datatype (int/str): " colType #
    if [[ "int" == "$colType" || "str" == "$colType" ]]
    then
        row+=:$colType
    else
        echo "Invalid Data Type "
        ((i--))
        continue
    fi  

 #pk
 if $pkFlag 
 then
    read -p "  Set as primary key? (yes/no): " isPrimaryKey
    if [[ "yes" =~ "$isPrimaryKey" ]]
    then
    row+=:PK
    pkFlag=false
    else
        if [[ "no" =~ "$isPrimaryKey" ]]
        then
               echo $row >> .$tableName"_metadata"  
             continue
        else
            echo " invalid choice "
            ((i--))
            continue
            
        fi
    fi

    fi
  echo $row >> .$tableName"_metadata"  
 
done

#awk -F : '{ printf "%s : ",$1 }' .$tableName"_metadata" > $tableName  #%s format pritnf like in c
while IFS=: read -r col _; do
    echo -n "$col:" >> $tableName
done < .$tableName"_metadata"
#sed -i 's/ : $//' $tableName
sed -i 's/:*$//' $tableName #remove last :
echo "" >> "$tableName" #when adding values in insert it skips first line
#awk -F ':' '{print $1}' .$tableName"_metadata" | paste -sd'|' - > "$tableName"
echo "Table '$tableName' created successfully with the following columns:"
 