#!/bin/bash

echo -e "\n"
echo "*********** Welcome To Database Management System ***********"
echo -e ""

# Ensure the Database directory exists
if [ -e ~/DBMS/Database ]; then
    cd ~/DBMS/Database
    echo "DBMS is ready"
else
    mkdir -p ~/DBMS/Database
    cd ~/DBMS/Database
    echo "DBMS is ready"
fi

COLUMNS=1
exit=true

while $exit; do
    PS3="Choose an option: "
    select name in "create database" "remove database" "list database" "connect to a database" "exit"; do
        echo
        case $name in
        "create database")
            read -p "Please enter database name: " dbName
            if [[ -d $dbName ]]; then
                echo "Database already exists."
                echo
            else
                mkdir "$dbName"
                echo "Database created successfully."
            fi
            ;;
        "remove database")
            read -p "Please enter the database name to delete: " dbName
            if [[ -d $dbName ]]; then
                rm -r "$dbName"
                echo "Database deleted successfully."
            else
                echo "No database found with this name."
            fi
            ;;
        "list database")
            if [[ -z "$(ls -A)" ]]; then
                echo "There are no databases."
            else
                ls -A
            fi
            ;;
        "connect to a database")
            read -p "Which database do you want to access? " dbName
            if [[ -d $dbName ]]; then
                # Call 'connect' script 
                 ../connect "$dbName"
            else
                echo
                echo "Please enter the name of an existing database."
            fi
            ;;
        "exit")
            exit=false
            break
            ;;
        *)
            echo "UNKNOWN OPTION"
            ;;
        esac
    done
done

