#!/bin/bash

tableName="$1"
metadataFile=".$tableName""_metadata"

# Check if the table's metadata file exists
if [[ ! -f "$metadataFile" ]]
then
    echo "Error: Table '$tableName' does not exist."
    exit 1
fi

size=$(cat "$metadataFile" | wc -l) #size of file as lines
#takes first row then print first field every loop[line]
awk -F ':' '
NR == 1 {
    for (i = 1; i <= NF; i++) {
        print i ": " $i
    }
}' "$tableName"
 
# Prompt the user to select a column by its number
read -p "Enter the column number to select or * to select all: " colChoice
if [[ $colChoice == "*" ]]
then
colChoice=0
fi 

# Function to display the selected column
display_column() {
    local columnIndex=$1 #0 #1 #colChoice
    echo "Displaying values :" #columnNames[0] = id
    echo                                                            #$1:$2:$3          # every loop in awk with every line #col choice sabet
    awk -F ':' -v col="$columnIndex" '{ print $col }' "$tableName"  #2:mano:44  $1 >> 2 ,, $2 >> mano >> $3 >> 44 --- $0 all >> 2:mano:44
} 

if [[ ! "$colChoice"  =~ ^[0-9]+$ && "$colChoice" != 0 ]] 
then
          echo "Error: Invalid column number"
          exit 1
    fi

 if [[ "$colChoice" -ge 1  && "$colChoice" -le "$size" ]]  #||"$colChoice" -eq 0 # || "$colChoice" == 0 
    then 
        # Display the selected colun
        display_column $((colChoice))
    else
        
        echo "Error: Invalid column number Out Of Size "
        exit 1
fi

